// Package containerdshim renders the containerd CRI configuration that
// selects platform-factory-shim (containerd-shim-platform-factory-v1) as the runtime
// for a CRI handler, using containerd's "shim" sandboxer.
//
// This is a deliberately different integration path from Podman's: Podman
// (and, formerly, this package) drive platform-factory-runtime directly as an
// io.containerd.runc.v2-style OCI-CLI facade. containerd's default
// "podsandbox" sandboxer reuses that same OCI-spec path for the pod sandbox
// itself, and unconditionally assigns the sandbox a fixed, non-empty Linux
// capability set that platform-factory-runtime deliberately refuses (see
// docs/containerd-kubernetes.md). platform-factory-shim gives containerd's CRI
// plugin a pod-scoped lifecycle controller that never presents an OCI spec
// for that policy to reject in the first place, delegating actual container
// creation back to the same platform-factory-runtime binary once a real container
// (not the sandbox metadata record) is being created.
package containerdshim

import (
	"fmt"
	"regexp"
)

const DefaultHandler = "platform-factory"

var handlerPattern = regexp.MustCompile(`^[a-z0-9]([-a-z0-9.]*[a-z0-9])?$`)

// runtimeType must match platform-factory-shim's own runtimeName constant: it is
// how containerd's shim manager derives the executable name it looks for on
// PATH (containerd-shim-platform-factory-v1, from this string's last two
// dot-separated segments).
const runtimeType = "io.containerd.platform-factory.v1"

type Config struct {
	// Handler is the CRI runtime handler name (Pod spec runtimeClassName /
	// crictl --runtime) this configuration registers. Defaults to
	// DefaultHandler.
	Handler string
}

func (c Config) normalized() (Config, error) {
	if c.Handler == "" {
		c.Handler = DefaultHandler
	}
	if !handlerPattern.MatchString(c.Handler) || len(c.Handler) > 63 {
		return Config{}, fmt.Errorf("containerd shim: invalid runtime handler %q", c.Handler)
	}
	return c, nil
}

// ContainerdConfig renders a containerd config-version-2 fragment. The main
// containerd config must import the directory containing this fragment.
func (c Config) ContainerdConfig() (string, error) {
	c, err := c.normalized()
	if err != nil {
		return "", err
	}
	const base = `# Generated by platform-factory-containerd. Do not edit.
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.%s]
  runtime_type = %q
  sandboxer = "shim"
  privileged_without_host_devices = false
  # containerd only copies CRI annotations into the OCI spec when they match
  # one of these glob patterns (they are dropped otherwise); platform-factory.dev/*
  # carries platform-factory-runtime's own direct-boot pin (kernel/init path and
  # digest) through from a Pod's container annotations. See
  # internal/ociruntime/supervisor_linux.go and rootfs_linux.go for what
  # reads them.
  pod_annotations = ["platform-factory.dev/*"]
  container_annotations = ["platform-factory.dev/*"]
`
	return fmt.Sprintf(base, c.Handler, runtimeType), nil
}

// RuntimeClass renders the Kubernetes selector for the configured CRI handler.
func (c Config) RuntimeClass() (string, error) {
	c, err := c.normalized()
	if err != nil {
		return "", err
	}
	return fmt.Sprintf(`apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: %s
handler: %s
`, c.Handler, c.Handler), nil
}
