package sbom

import (
	"bytes"
	"encoding/json"
	"testing"
)

// FuzzDocumentDecode feeds arbitrary bytes at the strict SBOM decode path
// (the same one platform-factory verify-release's --sbom uses). An SBOM file is
// attacker-controlled by construction: it's read back from disk, possibly
// generated by a third party, before being trusted as evidence.
func FuzzDocumentDecode(f *testing.F) {
	f.Add([]byte(`{"components":[{"name":"a","digest":"sha256:00","size":1,"kind":"binary"}]}`))
	f.Add([]byte(`{"components":[],"packages":[{"name":"x","version":"1","ecosystem":"go","source":"go.mod"}]}`))
	f.Add([]byte(`{"components":"not-an-array"}`))
	f.Add([]byte(`null`))
	f.Add([]byte(`{}`))

	f.Fuzz(func(t *testing.T, data []byte) {
		if len(data) > 1<<20 {
			t.Skip()
		}
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.DisallowUnknownFields()
		var document Document
		_ = decoder.Decode(&document)
	})
}
